version: '3'

services:
  wifi:
    #user: root
    image: "cyber5k/wifi:${MISTBORN_TAG}"
    container_name: mistborn_production_wifi
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.port=80"
    #env_file:
    #  - ../.envs/.production/.pihole
    #command: /start
    volumes:
      - ../../mistborn_volumes/extra/wifi/hostapd.conf:/etc/hostapd/hostapd.conf
      - ../../mistborn_volumes/extra/wifi/dnsmasq.conf:/etc/dnsmasq.conf
    #  - ../../mistborn_volumes/extra/wifi/wificfg.json:/cfg/wificfg.json
    network_mode: bridge #host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    #privileged: true

